name: Release Sheikh LLM

# Trigger on push tags like v1.0.0
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Build the runtime (llama.cpp)
      - name: Build Runtime
        run: |
          cd runtime
          make build
          cd ..

      # Package model, runtime, SDKs, examples
      - name: Package Release
        run: |
          tar -czf sheikh-release.tar.gz \
            model/sheikh.gguf \
            runtime/sheikh \
            sdk/python \
            sdk/node \
            examples/

      # Create GitHub Release and upload package
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Sheikh LLM ${{ github.ref_name }}
          files: sheikh-release.tar.gz

      # Optional: Publish Python SDK to PyPI
      - name: Publish Python SDK (Optional)
        if: false  # set to true to enable
        run: |
          cd sdk/python
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

      # Optional: Publish Node SDK to NPM
      - name: Publish Node SDK (Optional)
        if: false  # set to true to enable
        run: |
          cd sdk/node
          npm publish --access public
